### ISSUE TITLE
silly fetchPackageMetaData error for codemirror@5.45.0 Unexpected end of JSON input while parsing near

### ISSUE THREAD

**Issue by mmfei** [go-admin-team/go-admin-ui#12]
没部署起来......

## 编译的日志
```bash
4790 http fetch GET 304 https://registry.npmjs.org/codemirror 145ms (from cache)
4791 silly fetchPackageMetaData error for codemirror@5.45.0 Unexpected end of JSON input while parsing near '...xFxysdF42Swp81ovye85C'
4792 http fetch GET 304 https://registry.npmjs.org/fuse.js 116ms (from cache)
4793 silly fetchPackageMetaData error for fuse.js@3.4.4 Unexpected end of JSON input while parsing near '...4.0.6","vue-eslint-pa'
4794 http fetch GET 304 https://registry.npmjs.org/core-js 149ms (from cache)
4795 silly fetchPackageMetaData error for core-js@^2.6.11 Unexpected end of JSON input while parsing near '...m":"00eb6d6bf815471cc'
4796 http fetch GET 304 https://registry.npmjs.org/vuex 88ms (from cache)
4797 silly fetchPackageMetaData error for vuex@3.1.0 Unexpected end of JSON input while parsing near '...watch-helpers":"^1.1.'
4798 timing stage:rollbackFailedOptional Completed in 1ms
4799 timing stage:runTopLevelLifecycles Completed in 144167ms
4800 silly saveTree vue-element-admin@4.2.1
4800 silly saveTree +-- @riophae/vue-treeselect@0.4.0
4800 silly saveTree +-- axios@0.18.1
4800 silly saveTree +-- clipboard@2.0.4
4800 silly saveTree +-- driver.js@0.9.5
4800 silly saveTree +-- dropzone@5.5.1
4800 silly saveTree +-- echarts@4.2.1
4800 silly saveTree +-- element-ui@2.11.1
4800 silly saveTree +-- file-saver@2.0.1
4800 silly saveTree +-- js-cookie@2.2.0
4800 silly saveTree +-- jsonlint@1.6.3
4800 silly saveTree +-- jszip@3.2.1
4800 silly saveTree +-- normalize.css@7.0.0
4800 silly saveTree +-- nprogress@0.2.0
4800 silly saveTree +-- path-to-regexp@2.4.0
4800 silly saveTree +-- screenfull@4.2.0
4800 silly saveTree +-- showdown@1.9.1
4800 silly saveTree +-- solarlunar@2.0.7
4800 silly saveTree +-- sortablejs@1.8.4
4800 silly saveTree +-- tui-editor@1.3.3
4800 silly saveTree +-- vue-count-to@1.0.13
4800 silly saveTree +-- vue-cropper@0.5.2
4800 silly saveTree +-- vue-router@3.0.2
4800 silly saveTree +-- vue-splitpane@1.0.4
4800 silly saveTree +-- vue@2.6.10
4800 silly saveTree +-- vuedraggable@2.20.0
4800 silly saveTree `-- xlsx@0.14.1
4801 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...xFxysdF42Swp81ovye85C'
4801 verbose stack     at JSON.parse (<anonymous>)
4801 verbose stack     at parseJson (/usr/local/lib/node_modules/npm/node_modules/json-parse-better-errors/index.js:7:17)
4801 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/node-fetch-npm/src/body.js:96:50
4801 verbose stack     at runMicrotasks (<anonymous>)
4801 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:97:5)
4802 verbose cwd /app
4803 verbose Linux 4.19.76-linuxkit
4804 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
4805 verbose node v12.16.2
4806 verbose npm  v6.14.4
```

## dockerfile
```dockerfile
FROM node:lts 
# 创建 app 目录
WORKDIR /app
# 可选命令：
# RUN npm -g install serve
# RUN mkdir /src;
# COPY ./go-admin-ui/* /src
# RUN find /src/  -maxdepth 1 -mindepth 1  \! -name "node_modules"   \! -name "*.git" \! -name "dist"  -exec cp -rf {} /app/ \;
# 安装 app 依赖
# RUN npm install --only=production
# RUN npm install
# RUN npm build:prod
# COPY --from=node_build /app ./
COPY ./start.sh /
RUN chmod +x -R /start.sh;
VOLUME [ "/data1" , "/app" ]
EXPOSE 3000
#CMD ["serve", "-s", "dist", "-p", "8080"]
#CMD ["npm", "run" , "dev"]
CMD ["/start.sh"]
```

## 启动脚本
```bash
#!/bin/sh
npm cache clean --force
npm install
npm run dev
```

**Comment by shengdoushi** [comment]
您刷一下docker build 的cache试一下， 我这边使用您的 Dockerfile, start.sh 是可以过的
