### ISSUE TITLE
npm run dev  - Error: Cannot find module 'debug'

### ISSUE THREAD

**Issue by akko77** [go-admin-team/go-admin-ui#185]
> go-admin@2.0.6 dev /Library/peng/GO/goadmin/go-admin-ui
> vue-cli-service serve

internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'debug'
Require stack:
- /Library/peng/GO/goadmin/go-admin-ui/node_modules/_@vue_cli-service@4.5.17@@vue/cli-service/lib/Service.js
- /Library/peng/GO/goadmin/go-admin-ui/node_modules/_@vue_cli-service@4.5.17@@vue/cli-service/bin/vue-cli-service.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Library/peng/GO/goadmin/go-admin-ui/node_modules/_@vue_cli-service@4.5.17@@vue/cli-service/lib/Service.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Library/peng/GO/goadmin/go-admin-ui/node_modules/_@vue_cli-service@4.5.17@@vue/cli-service/lib/Service.js',
    '/Library/peng/GO/goadmin/go-admin-ui/node_modules/_@vue_cli-service@4.5.17@@vue/cli-service/bin/vue-cli-service.js'
  ]
}

这个错误怎么解决呀？

**Comment by akko77** [comment]
删除了原项目重新用命令安装：
npm install --registry=https://registry.npm.taobao.org

BUG原因是原来用了cnpm install
