### ISSUE TITLE
npm run dev failed

### ISSUE THREAD

**Issue by hoyah** [go-admin-team/go-admin-ui#194]
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'dev' ]
2 info using npm@6.14.4
3 info using node@v10.19.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle go-admin@2.0.6~predev: go-admin@2.0.6
6 info lifecycle go-admin@2.0.6~dev: go-admin@2.0.6
7 verbose lifecycle go-admin@2.0.6~dev: unsafe-perm in lifecycle true
8 verbose lifecycle go-admin@2.0.6~dev: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/ubuntu/go-admin-ui/node_modules/.bin:/home/ubuntu/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/bin/remote-cli:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle go-admin@2.0.6~dev: CWD: /home/ubuntu/go-admin-ui
10 silly lifecycle go-admin@2.0.6~dev: Args: [ '-c', 'vue-cli-service serve' ]
11 silly lifecycle go-admin@2.0.6~dev: Returned: code: 137  signal: null
12 info lifecycle go-admin@2.0.6~dev: Failed to exec dev script
13 verbose stack Error: go-admin@2.0.6 dev: `vue-cli-service serve`
13 verbose stack Exit status 137
13 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid go-admin@2.0.6
15 verbose cwd /home/ubuntu/go-admin-ui
16 verbose Linux 5.4.0-124-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "dev"
18 verbose node v10.19.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 137
22 error go-admin@2.0.6 dev: `vue-cli-service serve`
22 error Exit status 137
23 error Failed at the go-admin@2.0.6 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 137, true ]

```

**Comment by hoyah** [comment]
Resolved.

The running vm had a low memory setting. Change vm emory to 2G, then it runs well.
