### ISSUE TITLE
Node.js v18.12.0:  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ]

### ISSUE THREAD

**Issue by ruishawn** [go-admin-team/go-admin-ui#201]
```
> go-admin@2.0.6 dev
> vue-cli-service serve

 INFO  Starting development server...
10% building 2/5 modules 3 active ...by/all-projects/goadmin/go-admin-ui/node_modules/@vue/cli-plugin-eslint/node_modules/eslint-loader/index.js??ref--14-0!/home/bobby/all-projects/goadmin/go-admin-ui/src/main.jsError: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/bobby/all-projects/goadmin/go-admin-ui/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/bobby/all-projects/goadmin/go-admin-ui/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/bobby/all-projects/goadmin/go-admin-ui/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/bobby/all-projects/goadmin/go-admin-ui/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/bobby/all-projects/goadmin/go-admin-ui/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/bobby/all-projects/goadmin/go-admin-ui/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/bobby/all-projects/goadmin/go-admin-ui/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/bobby/all-projects/goadmin/go-admin-ui/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /home/bobby/all-projects/goadmin/go-admin-ui/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/home/bobby/all-projects/goadmin/go-admin-ui/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/home/bobby/all-projects/goadmin/go-admin-ui/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/home/bobby/all-projects/goadmin/go-admin-ui/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/bobby/all-projects/goadmin/go-admin-ui/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /home/bobby/all-projects/goadmin/go-admin-ui/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/bobby/all-projects/goadmin/go-admin-ui/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/bobby/all-projects/goadmin/go-admin-ui/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/bobby/all-projects/goadmin/go-admin-ui/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/bobby/all-projects/goadmin/go-admin-ui/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/bobby/all-projects/goadmin/go-admin-ui/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/bobby/all-projects/goadmin/go-admin-ui/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/bobby/all-projects/goadmin/go-admin-ui/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/home/bobby/all-projects/goadmin/go-admin-ui/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/bobby/all-projects/goadmin/go-admin-ui/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /home/bobby/all-projects/goadmin/go-admin-ui/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /home/bobby/all-projects/goadmin/go-admin-ui/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.12.0
```

**Comment by jiftle** [comment]
linux下，执行。export NODE_OPTIONS=--openssl-legacy-provider， 然后npm run dev
