### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'version')

### ISSUE THREAD

**Issue by 161424** [go-admin-team/go-admin-ui#218]
报错内容：
PS D:\Programs\go_admin\go-admin-ui> npm run dev

> go-admin@2.0.9 dev
> vue-cli-service serve

 ERROR  TypeError: Cannot read properties of undefined (reading 'version')
TypeError: Cannot read properties of undefined (reading 'version')
    at module.exports (D:\Programs\go_admin\go-admin-ui\node_modules\@vue\cli-plugin-eslint\index.js:20:27)
    at D:\Programs\go_admin\go-admin-ui\node_modules\@vue\cli-service\lib\Service.js:78:7
    at Array.forEach (<anonymous>)
    at Service.init (D:\Programs\go_admin\go-admin-ui\node_modules\@vue\cli-service\lib\Service.js:76:18)
    at Service.run (D:\Programs\go_admin\go-admin-ui\node_modules\@vue\cli-service\lib\Service.js:215:10)
    at Object.<anonymous> (D:\Programs\go_admin\go-admin-ui\node_modules\@vue\cli-service\bin\vue-cli-service.js:36:9)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)

尝试过程：更换3个版本的node未解决，均是这一个错误

解决方法：在package.json里将下图代码删除
"@vue/cli-plugin-eslint": "~4.5.0"

**Comment by wenjianzhang** [comment]
可以尝试yarn 进行安装

**Comment by wenjianzhang** [comment]
感谢反馈。

@vue/cli-plugin-eslint 已移除：

`package.json` 中已无任何 `@vue/cli-*` 依赖，构建入口为 `vite.config.mjs`。

代码基础已与提交时不同，问题无法在当前版本上核实，予以关闭。若类似问题在最新版本上仍然存在，欢迎另开 issue 说明。
